[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Tim Lazarus <me@timlazarus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
rayon = "1.5"
indicatif = "0.15.0"
image = "0.23.14"